services:
  - type: web
    name: brunch-app
    env: php
    region: frankfurt
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: cd public/ && php -S 0.0.0.0:$PORT
    envVars:
      - key: APP_NAME
        value: BRUNCH
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://${RENDER_SERVICE_NAME}.${RENDER_EXTERNAL_HOSTNAME}
      - key: LOG_CHANNEL
        value: errorlog
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: 5432
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false